const express = require('express');
const cors = require('cors');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');

const app = express();
const PORT = process.env.PORT || 5000;

// Middleware
app.use(cors());
app.use(express.json());

// Setup storage paths
const UPLOADS_DIR = path.join(__dirname, 'uploads');
const DEFAULTS_DIR = path.join(UPLOADS_DIR, 'defaults');
const DB_FILE = path.join(__dirname, 'database.json');

// Ensure directories exist
if (!fs.existsSync(UPLOADS_DIR)) {
  fs.mkdirSync(UPLOADS_DIR, { recursive: true });
}
if (!fs.existsSync(DEFAULTS_DIR)) {
  fs.mkdirSync(DEFAULTS_DIR, { recursive: true });
}

// Helper: Read Database
function readDB() {
  if (!fs.existsSync(DB_FILE)) {
    // Return default empty structure
    const initialDB = {
      users: [],
      loginLogs: [],
      downloadLogs: [],
      materials: []
    };
    fs.writeFileSync(DB_FILE, JSON.stringify(initialDB, null, 2));
    return initialDB;
  }
  try {
    const data = fs.readFileSync(DB_FILE, 'utf8');
    return JSON.parse(data);
  } catch (err) {
    console.error('Error reading database file, resetting:', err);
    return { users: [], loginLogs: [], downloadLogs: [], materials: [] };
  }
}

// Helper: Write Database
function writeDB(data) {
  try {
    fs.writeFileSync(DB_FILE, JSON.stringify(data, null, 2));
  } catch (err) {
    console.error('Error writing database file:', err);
  }
}

// Create default sample PDF documents
const defaultFiles = [
  { id: 'def-py-1', title: 'Python Basics Cheat Sheet', subjectCode: 'CS1139', category: 'notes', filename: 'python_basics.pdf', content: 'Python Programming 1 (CS1139) - Basics, Data Types, Control Flow, and Functions Study Notes.' },
  { id: 'def-py-2', title: 'PYQ End Term 2025', subjectCode: 'CS1139', category: 'papers', subcategory: 'end-term', filename: 'py_endterm_2025.pdf', content: 'Programming 1 (Python) End-Term Examination 2025. Q1: Explain list comprehensions. Q2: Implement binary search...' },
  { id: 'def-eee-1', title: 'EEE Mid Term 1 Solved Paper', subjectCode: 'EE1118', category: 'papers', subcategory: 'mid-term-1', filename: 'eee_mid1_2025.pdf', content: 'EEE (EE1118) Mid Term 1 Solutions. KVL, KCL, Thevenin Theorem, and Norton Theorem Solved Examples.' },
  { id: 'def-calc-1', title: 'Calculus Complete Formula Sheet', subjectCode: 'AS1109', category: 'formulas', filename: 'calculus_formulas.pdf', content: 'Calculus (AS1109) Formula Sheet. Derivatives, Integration formulas, Taylor series, and Limits theorems.' },
  { id: 'def-phys-1', title: 'Applied Physics Wave Optics Notes', subjectCode: 'AS1108', category: 'notes', filename: 'physics_optics.pdf', content: 'Applied Physics (AS1108) - Wave Optics, Interference, Diffraction, and Polarization notes.' },
  { id: 'def-evs-1', title: 'Environmental Science Important Topics', subjectCode: 'ES1115', category: 'topics', filename: 'evs_imp_topics.pdf', content: 'EVS (ES1115) Important Exam Topics. 1. Ecosystem Dynamics, 2. Global Warming, 3. Renewable Energy Resources, 4. Environmental Legislation.' },
  { id: 'def-fc-1', title: 'Fundamentals of Comm. Mid Term 2 Solved', subjectCode: 'CC1101', category: 'papers', subcategory: 'mid-term-2', filename: 'fc_mid2_solved.pdf', content: 'Fundamental of Communication (CC1101) Mid Term 2 Solved Paper. Modulation Index, Amplitude Modulation, and Frequency Modulation.' }
];

// Write default files on startup if they don't exist
defaultFiles.forEach(file => {
  const filePath = path.join(DEFAULTS_DIR, file.filename);
  if (!fs.existsSync(filePath)) {
    // Generate dummy content inside a fake PDF file (we write readable text, when downloaded it will act as a mock PDF/Text file)
    const mockPdfHeader = `%PDF-1.4\n% MOCK PDF FILE GENERATED BY BACKBENCHERS PORTAL\n\nSubject: ${file.subjectCode}\nTitle: ${file.title}\nCategory: ${file.category}\n\nContent:\n${file.content}\n\n--- END OF MOCK PDF ---`;
    fs.writeFileSync(filePath, mockPdfHeader);
  }
});

// Seed default materials in DB if empty
const db = readDB();
if (db.materials.length === 0) {
  db.materials = defaultFiles.map(file => ({
    id: file.id,
    title: file.title,
    subjectCode: file.subjectCode,
    category: file.category,
    subcategory: file.subcategory || null,
    filename: file.filename,
    filepath: `/uploads/defaults/${file.filename}`,
    isDefault: true,
    uploadedAt: new Date().toISOString()
  }));
  writeDB(db);
}

// Serve uploaded and default files static directories
app.use('/uploads/defaults', express.static(DEFAULTS_DIR));
app.use('/uploads', express.static(UPLOADS_DIR));

// Configure Multer for PDF uploads
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, UPLOADS_DIR);
  },
  filename: function (req, file, cb) {
    const ext = path.extname(file.originalname);
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
    cb(null, 'document-' + uniqueSuffix + (ext ? ext : '.pdf'));
  }
});

const upload = multer({
  storage: storage,
  fileFilter: function (req, file, cb) {
    // Only accept PDFs
    const ext = path.extname(file.originalname).toLowerCase();
    if (ext !== '.pdf') {
      return cb(new Error('Only PDF uploads are allowed!'));
    }
    cb(null, true);
  }
});

// --- API ROUTES ---

// Auth: Register
app.post('/api/auth/register', (req, res) => {
  const { name, email, password } = req.body;
  if (!name || !email || !password) {
    return res.status(400).json({ error: 'All fields are required' });
  }

  const dbData = readDB();
  const existingUser = dbData.users.find(u => u.email.toLowerCase() === email.toLowerCase());

  if (existingUser) {
    return res.status(400).json({ error: 'Email already registered' });
  }

  const newUser = {
    id: uuidv4(),
    name,
    email,
    password, // Store directly for simple mock db demonstration
    createdAt: new Date().toISOString()
  };

  dbData.users.push(newUser);
  writeDB(dbData);

  res.status(201).json({
    message: 'Registration successful',
    user: { id: newUser.id, name: newUser.name, email: newUser.email }
  });
});

// Auth: Login / Google Login
app.post('/api/auth/login', (req, res) => {
  const { email, password, isGoogleLogin, name } = req.body;

  if (!email) {
    return res.status(400).json({ error: 'Email is required' });
  }

  const dbData = readDB();
  let user = dbData.users.find(u => u.email.toLowerCase() === email.toLowerCase());

  if (isGoogleLogin) {
    // If Google login and user doesn't exist, create account on the fly (as requested: "student login kre gmail se agar uska pehle account createdd hai to , nhi to account create krke login kre")
    if (!user) {
      user = {
        id: uuidv4(),
        name: name || email.split('@')[0],
        email,
        password: 'OAuthMockPassword123',
        isGoogle: true,
        createdAt: new Date().toISOString()
      };
      dbData.users.push(user);
    }
  } else {
    // Normal email/password validation
    if (!user || user.password !== password) {
      return res.status(401).json({ error: 'Invalid email or password' });
    }
  }

  // Log the login event
  const loginLog = {
    id: uuidv4(),
    userId: user.id,
    name: user.name,
    email: user.email,
    timestamp: new Date().toISOString(),
    method: isGoogleLogin ? 'Google OAuth' : 'Email/Password'
  };
  dbData.loginLogs.unshift(loginLog); // Add to beginning
  writeDB(dbData);

  res.json({
    message: 'Login successful',
    user: { id: user.id, name: user.name, email: user.email }
  });
});

// Admin: Get all student login logs
app.get('/api/admin/logins', (req, res) => {
  const dbData = readDB();
  res.json(dbData.loginLogs);
});

// Admin: Get all download logs
app.get('/api/admin/downloads', (req, res) => {
  const dbData = readDB();
  res.json(dbData.downloadLogs);
});

// Admin: Get list of all registered students
app.get('/api/admin/users', (req, res) => {
  const dbData = readDB();
  // Return users summary (excluding passwords)
  const students = dbData.users.map(u => ({
    id: u.id,
    name: u.name,
    email: u.email,
    createdAt: u.createdAt,
    isGoogle: !!u.isGoogle
  }));
  res.json(students);
});

// Materials: Get all materials
app.get('/api/materials', (req, res) => {
  const dbData = readDB();
  res.json(dbData.materials);
});

// Materials: Upload a PDF (Admin)
app.post('/api/materials/upload', upload.single('file'), (req, res) => {
  const { title, subjectCode, category, subcategory } = req.body;

  if (!req.file) {
    return res.status(400).json({ error: 'Please upload a PDF file' });
  }
  if (!title || !subjectCode || !category) {
    return res.status(400).json({ error: 'Title, subject code, and category are required' });
  }

  const dbData = readDB();
  const newMaterial = {
    id: uuidv4(),
    title,
    subjectCode,
    category, // notes, papers, formulas, topics
    subcategory: subcategory || null, // e.g. mid-term-1, mid-term-2, end-term (used for papers)
    filename: req.file.filename,
    filepath: `/uploads/${req.file.filename}`,
    isDefault: false,
    uploadedAt: new Date().toISOString()
  };

  dbData.materials.push(newMaterial);
  writeDB(dbData);

  res.status(201).json({
    message: 'Material uploaded successfully',
    material: newMaterial
  });
});

// Materials: Log a download event (by a student)
app.post('/api/downloads', (req, res) => {
  const { name, email, subjectCode, title, filename } = req.body;
  if (!email || !filename) {
    return res.status(400).json({ error: 'Email and filename are required' });
  }

  const dbData = readDB();
  const downloadLog = {
    id: uuidv4(),
    name: name || 'Guest',
    email,
    subjectCode: subjectCode || 'N/A',
    title: title || filename,
    filename,
    timestamp: new Date().toISOString()
  };

  dbData.downloadLogs.unshift(downloadLog);
  writeDB(dbData);

  res.status(201).json({ message: 'Download logged successfully', log: downloadLog });
});

// Fallback error handler for multer
app.use((err, req, res, next) => {
  if (err instanceof multer.MulterError) {
    return res.status(400).json({ error: `Multer upload error: ${err.message}` });
  } else if (err) {
    return res.status(400).json({ error: err.message });
  }
  next();
});

// Start the server
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
  console.log(`Default materials seeded. Database at: ${DB_FILE}`);
});
